site_name: IDEMS Sidekick
theme:
  name: material
  palette:
    primary: black
    accent: a mber
  font:
    text: "Open Sans"
  favicon: assets/images/idems_logo.png
  logo: assets/images/idems_logo.png
repo_url: https://github.com/IDEMSInternational/sidekick
edit_uri: edit/master/documentation/docs/

nav:
  - Intro: index.md
  - Set up: setup/setup.md
  - Editing Content:
          - editing-content/adding-articles.md
          - editing-content/editing.md
  - Validation:
      - validation/validation.md
  - Pushing Content:
      - pushing-content/push.md
  - Images and Assets:
      - assets/assets.md
  - Help:
      - help/privacy-policy.md
      - help/support.md
      - help/terms-of-service.md


markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde