name: Documentation - Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: app-sidekick.idems.international
          CONFIG_FILE: documentation/mkdocs.yml
          REQUIREMENTS: documentation/requirements.txt
